export default function Bg() {
  return (
    <>
      <div className="w-screen h-screen bg-slate-950 grid grid-cols-12 relative before:absolute before:contents[''] before:bottom-0 before:right-0 before:w-[100px] before:rounded-l-full before:h-screen before:bg-blue-500 before:blur-[120px]">
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
        <div className="border border-slate-900/40"></div>
      </div>
    </>
  );
}
